### ISSUE TITLE
Unnecessary require and panic?

### ISSUE THREAD

**Issue by mattlockyer** [keypom/keypom#67]
We require there be registered uses before refunding assets, but I don't think we need to panic.

Can we simply return from the method at this point?

It's messing up my batch calls, I have 2 functionCall actions in a single TX and because this is failing the other delete_keys call is failing.

https://github.com/keypom/keypom/blob/2fd35fb74bf54a89d1c4c1b3ab24718e5adfdc62/contract/src/stage1/delete.rs#L379

**Comment by mattlockyer** [comment]
I just check registered_uses now, but I'm still wondering if it warrants a panic at this point or if we can just ignore and return since there's no side effect?

**Comment by BenKurrek** [comment]
This is a bug and should be fixed. Attack vector if someone with no claims drains their key and then they register a use and key gets deleted prompting a refund for more than they should receive.
