### ISSUE TITLE
[IDEA] Allow for clearing all drops by owner

### ISSUE THREAD

**Issue by joe-rlo** [keypom/keypom#81]
It would be a nice-to-have if the owner of the drops could clear all unclaimed drops in one call.

For example, with ShardDog, we get a bunch of people who will checkout how the automatic link works but then not claim the drop. So currently we need to go back and clear out each drop seperately.

Thanks!

**Comment by jaswinder6991** [comment]
This would be helpful.

**Comment by BenKurrek** [comment]
After consideration, it seems like this is best suited to live in an SDK or a helper method that is outside the scope of the protocol. For example, we've implemented something similar [here](https://github.com/keypom/keypom-js#Delete-Drops) which can be used by people. Feel free to re-open the issue if you believe it should live on the protocol level.
