### ISSUE TITLE
Adding account_id_field in a nested way in FC args. Examples adding a proposal to a DAO.

### ISSUE THREAD

**Issue by jaswinder6991** [keypom/keypom#83]
If you want your linkdrop to add a proposal to the DAO to add the new claimed account, this is how the arguments look like:
`
{
          proposal: {
            description: "Add a new claimer to DAO",
            kind: {
              AddMemberToRole: {
                member_id: "",
                role: "Council"
              }
            }
          }
`

Here you want to put account_id_field to the member_id in the args. However the member_id id a nested element in the args. To access that you gotta go in proposal, then kind, then AddMemberToRole. The current FC functionality only adds account_id_field as a 1st level json key pair. Like owner or recieved_id in nft_mint function. 
If you look at the FC code where you added account_id, it looks as follows:
`
 if let Some(field) = method.account_id_field.as_ref() {
                final_args.insert_str(
                    final_args.len() - 1,
                    &format!(",\"{}\":\"{}\"", field, account_id),
                );
                near_sdk::log!(
                    "Adding claimed account ID to specified field: {:?}",
                    method.account_id_field,
                );
            }
`

which just appends it at the end of the args at the 1st level. But if you want it at a nested key, it won't work.
Hence you can't do a DAO membership addition drop or any other FC which needs placement at a nested key.
As a non, rust dev, I wrote a simple for loop to achieve this and successfully tested it on testnet as well. 

`
if claim_succeeded {
            let final_args = args.clone();

            // Add the account ID that claimed the linkdrop as part of the args to the function call in the key specified by the user
            // if let Some(account_field) = claimed_account_field {
            //     final_args.insert_str(final_args.len()-1, &format!(",\"{}\":\"{}\"", account_field, account_id));
            //     env::log_str(&format!("Adding claimed account ID to specified field: {:?} in args: {:?}", account_field, args));
            // }
            
            let mut v: Value = serde_json::from_str(&final_args.to_string()).unwrap();
            if let Some(account_field) = claimed_account_field {
                //get the nested key path of new key-value pair
                let mut key_path: Vec<&str> = account_field.split(".").collect();
                let key = key_path.remove(key_path.len()-1);

                // Parse the string of data into serde_json::Value.
                //let mut v: Value = serde_json::from_str(final_args).unwrap();
                //This line checks the usecase where you add the key
                //value pair at the parent level
                let mut temp = &mut v;
                //try to do 
                for s in key_path {
                    temp = &mut temp[s];
                }
                if let Value::Object(m) = temp{
                    m.insert(key.to_string(), Value::String(account_id.to_string()));
                };
                env::log_str(&format!("Added claimed account ID to specified field: {:?} in args: {:?}", account_field, v.to_string()));             
            }
            let final_args2 = &v.to_string();
            //env::log_str(&format!("Added claimed account ID to specified field: {:?} in args: {:?}", account_field, final_args2));             
            
            env::log_str(&format!("Attaching Total: {:?} Deposit: {:?} Should Refund?: {:?} Amount To Refund: {:?} With args: {:?}", yocto_to_near(deposit.0 + if add_refund_to_deposit.unwrap_or(false) {amount_to_refund} else {0}), yocto_to_near(deposit.0), add_refund_to_deposit.unwrap_or(false), yocto_to_near(amount_to_refund), final_args2));

            // Call function with the min GAS and deposit. all unspent GAS will be added on top
            Promise::new(receiver).function_call_weight(
                method, 
                final_args2.as_bytes().to_vec(), 
                // The claim is successful so attach the amount to refund to the deposit instead of refunding the funder.
                deposit.0 + if add_refund_to_deposit.unwrap_or(false) {amount_to_refund} else {0}, 
                MIN_GAS_FOR_CALLBACK_FUNCTION_CALL,
                GasWeight(1)
            );
        }
`

I have read further and find out, this can be done without a for loop too. I can share that code snippet as well.

**Comment by jaswinder6991** [comment]
Adding a version of the above code without the for loop.

`
if claim_succeeded {
let final_args = args.clone();

        // Add the account ID that claimed the linkdrop as part of the args to the function call in the key specified by the user
        
        let mut v: Value = serde_json::from_str(&final_args.to_string()).unwrap();
        if let Some(account_field) = claimed_account_field {
            //get the nested key path of new key-value pair
            let mut key_path: Vec<&str> = account_field.split(".").collect();
            let key = key_path.remove(key_path.len()-1);
            
           // replacing the for loop with .fold() to reach to the last element.
            let temp = key_path.iter().fold(&mut v, |map, item|  &mut map[item]);

            if let Value::Object(m) = temp{
                m.insert(key.to_string(), Value::String(account_id.to_string()));
            };
            env::log_str(&format!("Added claimed account ID to specified field: {:?} in args: {:?}", account_field, v.to_string()));             
        }
        let final_args2 = &v.to_string();
        //env::log_str(&format!("Added claimed account ID to specified field: {:?} in args: {:?}", account_field, final_args2));             
        
        env::log_str(&format!("Attaching Total: {:?} Deposit: {:?} Should Refund?: {:?} Amount To Refund: {:?} With args: {:?}", yocto_to_near(deposit.0 + if add_refund_to_deposit.unwrap_or(false) {amount_to_refund} else {0}), yocto_to_near(deposit.0), add_refund_to_deposit.unwrap_or(false), yocto_to_near(amount_to_refund), final_args2));

        // Call function with the min GAS and deposit. all unspent GAS will be added on top
        Promise::new(receiver).function_call_weight(
            method, 
            final_args2.as_bytes().to_vec(), 
            // The claim is successful so attach the amount to refund to the deposit instead of refunding the funder.
            deposit.0 + if add_refund_to_deposit.unwrap_or(false) {amount_to_refund} else {0}, 
            MIN_GAS_FOR_CALLBACK_FUNCTION_CALL,
            GasWeight(1)
        );
    }

`

**Comment by BenKurrek** [comment]
Fixed in https://github.com/keypom/keypom/pull/93
